### ISSUE TITLE
Ovishap

### ISSUE THREAD

**Issue by saadman-sakib** [NirobNabil/iut_gamejam24#1]
Tomra shobai thako shukhe agun joluk amar buke 😊

**Comment by NirobNabil** [comment]
@arbanhossain @Rabbani2019331039 please check this issue. This should be solved in our next release

**Comment by arbanhossain** [comment]
This issue is now resolved after the latest commit: b1d3c0b12fbe5e282ddd98debb8ed4be1dba6094 I am marking this issue as closed. Cheers!
